name: Publish to PyPI and publish docs

on:
  push:
    tags:
     - '*'

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions

    - name: Test with tox
      run: tox

  build-n-publish:
    name: Build and publish Python distributions to PyPI
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install pypa/setuptools
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        python -m pip install tox tox-gh-actions

    - name: Extract tag name
      id: tag
      run: echo ::set-output name=TAG_NAME::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Update version in setup.py
      run: >-
        sed -i "s/{{VERSION_PLACEHOLDER}}/${{ steps.tag.outputs.TAG_NAME }}/g" setup.py

    - name: Build a binary wheel
      run: >-
        python setup.py sdist bdist_wheel

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: Generate coverage asset
      run: tox -r coverage

    - name: install doc deps
      run: >-
        pip install sphinx
        pip install sphinx-autodoc-construct

    - name: Sphinx docs to GitHub Pages
      uses: uibcdf/action-sphinx-docs-to-gh-pages@v2.0.0
      with:
        branch: master
        dir_docs: docs/source
